### PR TITLE
Modified Int64List types to work on web

### PR DESCRIPTION
**Pull request by redsolver**

### CODE REVIEW

**Comment by ilap** [comment]
Thx for the contribution, I will check the PR today or max tomorrow.

**Comment by ilap** [comment]
These changes are breaking tests and examples.
I will give it some 2nd thought how can I get rid off the fixnum packages.

**Comment by ilap** [comment]
Hey, thx, but I have refactored the code for working /w JS and Web Dart.
So, pls test it with the v0.2.0-nullsafety.7.

**Comment by redsolver** [comment]
Thank you!

**Pull request closed without merging**
