### PR TITLE
Web implemenation seperate from Native dart

### PR DESCRIPTION
**Pull request by marcov-dart**
This PR is an update from my previous PR and just intended as FYI.

I have separated the web implementation by adding my previous code as tweetnacl_web.dart and tweetnacl_web_ext.dart, created two new files tweetnacl_stub.dart and tweetnacl_stub_ext.dart as placeholders to keep the analyzer happy and modified api.dart to conditionally export either tweetnacl.dart or tweetnacl_web.dart.

### CODE REVIEW

**Comment by ilap** [comment]
Hey, thx, but I have refactored the code for working /w JS and Web Dart.
So, pls test the v0.2.0-nullsafety.7 version

**Comment by ilap** [comment]
I am closing this as it's already been resolved in the master branch for some time.

**Comment by marcov-dart** [comment]
Confirmed. I tested using ^0.2.0-nullsafety.9
Is working ok for me. Both native serverside and JS on Web.

**Comment by ilap** [comment]
Cool thx, for confirming.

**Pull request closed without merging**
